import 'bootstrap/dist/css/bootstrap.min.css';
import './src/styles/navigations.css'
import './src/styles/hamburger.css'
import "bootstrap-icons/font/bootstrap-icons.css"
import "./src/styles/frontPage.css"
import "./src/styles/aboutMe.css"
import "./src/styles/experience.css"
import "./src/styles/projects.css"
import "./src/styles/education.css"
import "./src/styles/contact.css"
import "./src/styles/footer.css"