import 'bootstrap/dist/css/bootstrap.min.css';
import './src/styles/myPortfolio/navigations.css'
import './src/styles/myPortfolio/hamburger.css'
import "bootstrap-icons/font/bootstrap-icons.css"
import "./src/styles/myPortfolio/frontPage.css"
import "./src/styles/myPortfolio/aboutMe.css"
import "./src/styles/myPortfolio/experience.css"
import "./src/styles/myPortfolio/projects.css"
import "./src/styles/myPortfolio/education.css"
import "./src/styles/myPortfolio/contact.css"
import "./src/styles/myPortfolio/footer.css"
import "./src/styles/myPortfolio/comingSoon.css"
import "./src/styles/CvTemplate/cvFooter.css"
import "./src/styles/CvTemplate/leftColumn.css"
import "./src/styles/CvTemplate/rightColumn.css"
import "./src/styles/portfolioTemplate/navbar.css"
import "./src/styles/portfolioTemplate/mainSection.css"
import "./src/styles/portfolioTemplate/aboutMePortfolio.css"